name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Test
        run: |
          go mod verify
          go mod download
          go test -race ./...
